apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "act-runner.fullname" . }}-config
  labels:
    {{- include "act-runner.labels" . | nindent 4 }}
data:
    {{- with .Values.data }}
    config.yaml: >-
        {{- toYaml . | nindent 8 }}
    {{- end }}