apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: act-runner-data
  labels:
    {{- include "act-runner.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
